In [1]:
import numpy as np
import matplotlib.pyplot as plt
from string import ascii_uppercase as alc
from random import randint
from numpy.lib.stride_tricks import sliding_window_view as swv

In [2]:
SMALL_DIAMOND = np.array(
    [
        ['', '', 'A', '', ''],
        ['', 'B', '', 'C', ''],
        ['D', '', 'E', '', 'F'],
        ['', 'G', '', 'H', ''],
        ['', '', 'I', '', '']
    ]
)
SMALL_DIAMOND

array([['', '', 'A', '', ''],
       ['', 'B', '', 'C', ''],
       ['D', '', 'E', '', 'F'],
       ['', 'G', '', 'H', ''],
       ['', '', 'I', '', '']], dtype='<U1')

In [3]:
REG_DIAMOND = np.array(
    [
        ['', '', 'A', '', 'B', '', 'C', '', ''],
        ['', 'D', '', 'E', '', 'F', '', 'G', ''],
        ['H', '', 'I', '', 'J', '', 'K', '', 'L'],
        ['', 'M', '', 'N', '', 'O', '', 'P', ''],
        ['', '', 'Q', '', 'R', '', 'S', '', '']
    ]
)
REG_DIAMOND

array([['', '', 'A', '', 'B', '', 'C', '', ''],
       ['', 'D', '', 'E', '', 'F', '', 'G', ''],
       ['H', '', 'I', '', 'J', '', 'K', '', 'L'],
       ['', 'M', '', 'N', '', 'O', '', 'P', ''],
       ['', '', 'Q', '', 'R', '', 'S', '', '']], dtype='<U1')

In [8]:
class Diamond:
    def __init__(self, size='regular', minimum=1, maximum=6):
        self.size = size
        self.letter_matrix = SMALL_DIAMOND if self.size == 'small' else REG_DIAMOND
        ### Building number matrix
        nbm = np.zeros(self.letter_matrix.shape, dtype=np.uint8)
        fill_boolean = self.letter_matrix != ''
        nbm[fill_boolean] = np.random.randint(minimum, maximum, fill_boolean.sum())
        self.number_matrix = nbm
        self.goal = self.get_goal()
    
    def print_letter_matrix(self):
        print(self.letter_matrix)
    
    def print_number_matrix(self):
        print(self.number_matrix)
    
    def get_goal(self):
        windows = swv(self.number_matrix, (3,3))
        diags = np.vstack([
            np.diagonal(windows, axis1=-2, axis2=-1).reshape(-1,3),
            np.diagonal(windows[..., ::-1], axis1=-2, axis2=-1).reshape(-1,3)
        ]).tolist()
        diags = np.array([d for d in diags if not 0 in d])
        return np.random.choice(diags.sum(axis=1))
    
    def guess(self, letters):
        cumsum = 0
        for letter in letters:
            idx = np.argwhere(self.letter_matrix==letter)[0]
            cumsum += self.number_matrix[idx[0], idx[1]]
        if cumsum == self.goal:
            return 1
        else:
            return -1

In [9]:
diamond = Diamond()
diamond.print_number_matrix()
diamond.print_letter_matrix()
print(diamond.goal)

[[0 0 4 0 2 0 3 0 0]
 [0 1 0 1 0 3 0 4 0]
 [5 0 3 0 2 0 5 0 2]
 [0 2 0 1 0 5 0 1 0]
 [0 0 4 0 4 0 5 0 0]]
[['' '' 'A' '' 'B' '' 'C' '' '']
 ['' 'D' '' 'E' '' 'F' '' 'G' '']
 ['H' '' 'I' '' 'J' '' 'K' '' 'L']
 ['' 'M' '' 'N' '' 'O' '' 'P' '']
 ['' '' 'Q' '' 'R' '' 'S' '' '']]
6


In [12]:
diamond.guess('BEI')

1

In [63]:
a[np.argwhere(b=='A')[0][0], np.argwhere(b=='A')[0][1]]

1

In [54]:
type('ABD')

str

In [51]:
diamond.goal

8

In [45]:
windows = swv(a, (3,3))

In [46]:
diagonals = np.diagonal(windows, axis1=-2, axis2=-1)
diagonals

array([[[0, 5, 2],
        [0, 0, 0],
        [1, 2, 1],
        [0, 0, 0],
        [5, 4, 2],
        [0, 0, 0],
        [3, 2, 3]],

       [[0, 0, 0],
        [5, 2, 1],
        [0, 0, 0],
        [2, 1, 1],
        [0, 0, 0],
        [4, 2, 2],
        [0, 0, 0]],

       [[4, 2, 1],
        [0, 0, 0],
        [2, 1, 3],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0],
        [2, 2, 0]]], dtype=uint8)

In [47]:
anti_diagonals = np.diagonal(windows[..., ::-1], axis1=-2, axis2=-1)
anti_diagonals

array([[[1, 5, 4],
        [0, 0, 0],
        [5, 2, 2],
        [0, 0, 0],
        [3, 4, 1],
        [0, 0, 0],
        [0, 2, 2]],

       [[0, 0, 0],
        [2, 2, 2],
        [0, 0, 0],
        [4, 1, 1],
        [0, 0, 0],
        [2, 2, 1],
        [0, 0, 0]],

       [[2, 2, 0],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0],
        [2, 1, 3],
        [0, 0, 0],
        [3, 2, 1]]], dtype=uint8)

In [37]:
diags = np.vstack([
    diagonals.reshape(-1,3),
    anti_diagonals.reshape(-1,3)
]).tolist()
diags = np.array([d for d in diags if not 0 in d])
diags

array([[1, 2, 1],
       [5, 4, 2],
       [3, 2, 3],
       [5, 2, 1],
       [2, 1, 1],
       [4, 2, 2],
       [4, 2, 1],
       [2, 1, 3],
       [1, 1, 1],
       [1, 5, 4],
       [5, 2, 2],
       [3, 4, 1],
       [2, 2, 2],
       [4, 1, 1],
       [2, 2, 1],
       [1, 1, 1],
       [2, 1, 3],
       [3, 2, 1]])

In [42]:
np.random.choice(diags.sum(axis=1))

8